<a href="https://colab.research.google.com/github/mhadi28/Binance_DataCollections/blob/main/Data_Collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install python-binance

Collecting python-binance
  Downloading python_binance-1.0.16-py2.py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 3.1 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from python-binance) (2.23.0)
Collecting dateparser
  Downloading dateparser-1.1.1-py2.py3-none-any.whl (288 kB)
     |████████████████████████████████| 288 kB 24.5 MB/s
Collecting websockets
  Downloading websockets-10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (112 kB)
     |████████████████████████████████| 112 kB 49.4 MB/s
Collecting ujson
  Downloading ujson-5.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (45 kB)
     |████████████████████████████████| 45 kB 2.6 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from python-binance) (1.15.0)
Collecting aiohttp
  Downloading aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 21.8 MB/s
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (4.2.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (21.4.0)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
     |████████████████████████████████| 144 kB 27.4 MB/s
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->python-binance) (2.0.12)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 52.4 MB/s
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (94 kB)
     |████████████████████████████████| 94 kB 3.4 MB/s
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/dist-packages (from yarl<2.0,>=1.0->aiohttp->python-binance) (2.10)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2.8.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2022.1)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27,<2022.3.15 in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (2019.12.20)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/dist-packages (from dateparser->python-binance) (1.5.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->python-binance) (3.0.4)
Installing collected packages: multidict, frozenlist, yarl, asynctest, async-timeout, aiosignal, websockets, ujson, dateparser, aiohttp, python-binance
Successfully installed aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 asynctest-0.13.0 dateparser-1.1.1 frozenlist-1.3.0 multidict-6.0.2 python-binance-1.0.16 ujson-5.2.0 websockets-10.3 yarl-1.7.2

In [ ]:
from binance import *
import pandas as pd
import numpy as np
import csv
from datetime import datetime

In [ ]:
client = Client()
raw_data = client.get_historical_klines('ETHUSDT', client.KLINE_INTERVAL_1HOUR, '1-Apr-2022', '30-Apr-2022')
raw_data

In [ ]:
data = 'ETH_1H.csv'
target = open(data, 'w', newline='')
candle_writer = csv.writer(target, delimiter=',')

In [ ]:
for i in raw_data:
  candle_writer.writerow(i)
target.close()

In [ ]:
csv_data = np.genfromtxt(data, delimiter=',')
csv_data

array([[1.64877120e+12, 3.28151000e+03, 3.30867000e+03, ...,
        9.35103510e+03, 3.07792804e+07, 0.00000000e+00],
       [1.64877480e+12, 3.30097000e+03, 3.30098000e+03, ...,
        1.12480910e+04, 3.68605534e+07, 0.00000000e+00],
       [1.64877840e+12, 3.25699000e+03, 3.26340000e+03, ...,
        1.65085168e+04, 5.34249566e+07, 0.00000000e+00],
       ...,
       [1.65126960e+12, 2.80781000e+03, 2.82300000e+03, ...,
        5.65225320e+03, 1.58867237e+07, 0.00000000e+00],
       [1.65127320e+12, 2.81926000e+03, 2.82317000e+03, ...,
        4.02074820e+03, 1.13226955e+07, 0.00000000e+00],
       [1.65127680e+12, 2.81713000e+03, 2.82965000e+03, ...,
        6.06752080e+03, 1.71240804e+07, 0.00000000e+00]])

In [ ]:
df = pd.DataFrame(csv_data[:1000, 0:6], columns=['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume'])
df.head()

      Timestamp     Open     High      Low    Close      Volume
0  1.648771e+12  3281.51  3308.67  3272.47  3300.98  17389.6189
1  1.648775e+12  3300.97  3300.98  3247.76  3256.98  26577.4276
2  1.648778e+12  3256.99  3263.40  3210.68  3225.93  38475.0941
3  1.648782e+12  3225.93  3250.61  3218.59  3250.29  19171.7963
4  1.648786e+12  3250.29  3258.76  3246.75  3247.33  15446.2725

In [ ]:
df.shape

(697, 6)

In [ ]:
df['Index'] = pd.to_datetime(df['Timestamp'],unit='ms')
df.tail()

,Timestamp,Open,High,Low,Close,Volume,Index
692,1.651262e+12,2792.95,2815.09,2789.07,2807.18,24464.9727,2022-04-29 20:00:00
693,1.651266e+12,2807.17,2818.15,2801.36,2807.80,11400.3942,2022-04-29 21:00:00
694,1.651270e+12,2807.81,2823.00,2795.45,2819.26,10493.4218,2022-04-29 22:00:00
695,1.651273e+12,2819.26,2823.17,2809.08,2817.13,8155.2347,2022-04-29 23:00:00
696,1.651277e+12,2817.13,2829.65,2812.19,2826.25,12361.7090,2022-04-30 00:00:00

In [ ]:
df = df.set_index('Index')
df

,Timestamp,Open,High,Low,Close,Volume
Index,,,,,,
2022-04-01 00:00:00,1.648771e+12,3281.51,3308.67,3272.47,3300.98,17389.6189
2022-04-01 01:00:00,1.648775e+12,3300.97,3300.98,3247.76,3256.98,26577.4276
2022-04-01 02:00:00,1.648778e+12,3256.99,3263.40,3210.68,3225.93,38475.0941
2022-04-01 03:00:00,1.648782e+12,3225.93,3250.61,3218.59,3250.29,19171.7963
2022-04-01 04:00:00,1.648786e+12,3250.29,3258.76,3246.75,3247.33,15446.2725
...,...,...,...,...,...,...
2022-04-29 20:00:00,1.651262e+12,2792.95,2815.09,2789.07,2807.18,24464.9727
2022-04-29 21:00:00,1.651266e+12,2807.17,2818.15,2801.36,2807.80,11400.3942
2022-04-29 22:00:00,1.651270e+12,2807.81,2823.00,2795.45,2819.26,10493.4218
2022-04-29 23:00:00,1.651273e+12,2819.26,2823.17,2809.08,2817.13,8155.2347
2022-04-30 00:00:00,1.651277e+12,2817.13,2829.65,2812.19,2826.25,12361.7090

In [ ]:
from google.colab import files

df.to_csv('ETH_1H.csv', encoding = 'utf-8-sig') 
files.download('ETH_1H.csv')